version: '2'
services:
  php:
    command: 'php-fpm'
    ports: ''
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        PHP_UPSTREAM: php
    networks:
      - backend
    ports:
      - '8000:8000'
